# Enable stateless CSRF protection for forms and logins/logouts
framework:
    csrf_protection:
        stateless_token_ids:
            - submit
            - authenticate
            - logout
    form:
        csrf_protection:
            token_id: submit